export type CaseFile = {
  slug: string;
  title: string;
  question: string;
  hook: string;
  category: string;
  reviewed: string;
  conventional: string;
  alternative: string;
  readTime: string;
  overview: string;
  story: { heading: string; body: string[] }[];
  sharedFacts: string[];
  unresolved: string[];
  timeline: { date: string; event: string; status: "Confirmed" | "Reported" | "Disputed" }[];
  evidenceCards: { title: string; theory: string; record: string; sourceIds: string[] }[];
  sources: { id: string; title: string; publisher: string; type: string; url: string }[];
};

export const cases: CaseFile[] = [
  {
    slug: "flat-earth", title: "Flat Earth", question: "Is the Earth a globe or a plane?",
    hook: "Humanity settled this one 2,200 years ago with a stick and a shadow. The internet un-settled it. This is the purest they-say-this, we-say-that fight on the site.",
    category: "Science & reality", reviewed: "July 2026",
    conventional: "Earth is an oblate spheroid roughly 12,742 km across. This follows from thousands of independent, repeatable observations—ship visibility, star positions, time zones, eclipse shadows, circumnavigation, satellite operation, and direct photography from space—and it is assumed correctly by every working GPS device, airline route, and astronomical prediction.",
    alternative: "Modern flat-earthers hold that Earth is a disc—usually with the North Pole at the center and Antarctica as an ice wall rim—that photos from space are fabricated, that gravity is an illusion of density or upward acceleration, and that a coordinated establishment conceals the truth.",
    readTime: "15 min",
    overview: "The globe was established science by the 3rd century BCE, when Eratosthenes measured Earth's circumference using shadows in two Egyptian cities—getting remarkably close with a stick and geometry. Modern flat-earth belief is not a survival of ancient thinking but a 19th-century invention, revived by internet video in the 2010s into the most famous they-say/we-say argument alive. It earns its place here as the control case: the one where the record can be checked by anyone, tonight, for free.",
    story: [
      { heading: "A stick, a well, and the size of the world", body: [
        "Around 240 BCE, Eratosthenes—chief librarian at Alexandria—heard that at noon on the summer solstice, sunlight reached the bottom of a well at Syene, while at the same moment in Alexandria a vertical stick cast a shadow at about seven degrees. Seven degrees is roughly a fiftieth of a circle; multiply the distance between the cities by fifty and you have the circumference of the Earth. His answer was in the right range within a few percent.",
        "The point of the story isn't the precision—it's the date. The educated world has known the Earth's shape, and even its approximate size, for more than two thousand years. Medieval scholars knew it; Columbus's dispute with his critics was about the size of the globe, never its shape. The 'everyone believed the Earth was flat until Columbus' story is itself a 19th-century myth.",
        "Which makes the modern movement stranger than it first appears: flat-earth belief is not ancient wisdom lingering. It is a Victorian invention with a YouTube revival." ] },
      { heading: "Rowbotham's experiment and the internet's algorithm", body: [
        "In 1849, English inventor Samuel Rowbotham waded into a drainage canal in Cambridgeshire—the Old Bedford Level—and reported that a boat six miles off remained visible when curvature should have hidden it. He named his system 'Zetetic Astronomy,' founded a movement, and debated scientists for decades. When the experiment was repeated carefully in 1870 with proper controls for atmospheric refraction, the curvature appeared exactly as predicted—but the movement survived its own falsification, a pattern it has never broken.",
        "The 20th-century Flat Earth Society dwindled to a mailing list. Then, around 2014, recommendation algorithms discovered that flat-earth videos held attention superbly. A fringe of a fringe became a global subculture with conferences, celebrities, and its own experimental program.",
        "The 2018 documentary 'Behind the Curve' captured the movement's defining moment: believers bought a $20,000 ring-laser gyroscope to prove the Earth stands still. It measured a 15-degree-per-hour drift—the rotation of the Earth—on the first try. They concluded the result could not be accepted." ] },
      { heading: "Tests anyone can run", body: [
        "The globe's real advantage is not authority—it's that the tests are free and repeatable by anyone. Watch a ship sail out: it vanishes hull-first, mast-last, and a camera zoom will not bring the hull back. Call a friend three time zones away at sunset and ask what the sun is doing. Fly, or track flights, in the southern hemisphere: Sydney to Santiago crosses the Pacific in about 12 hours—possible on a globe, absurd on a north-centered disc where that route stretches across the entire map.",
        "Watch the sky: the southern hemisphere sees its own stars rotating clockwise around a southern celestial pole, invisible from the north—impossible over a disc where every southern observer faces outward toward different edges. Watch a lunar eclipse: Earth's shadow on the Moon is always round, from every angle, at every hour it occurs—only a sphere casts a round shadow in all orientations.",
        "And every day, silently, the practical world runs on the globe: GPS satellites correcting for orbital geometry and relativity, airlines flying great-circle routes over the poles, surveyors and ship captains and astronomers all using spherical math that would fail visibly, immediately, if the shape were wrong. There is no flat-earth GPS, no flat-earth airline, no flat-earth eclipse prediction—because no flat model produces one that works." ] }
    ],
    sharedFacts: ["Ships disappear hull-first over the horizon and zoom does not bring the hull back.", "The southern hemisphere has its own celestial pole with stars rotating around it.", "Sydney–Santiago and similar southern routes fly in times only a globe's geometry allows.", "Earth's shadow on the Moon during lunar eclipses is always circular.", "A flat-earth-funded ring-laser gyroscope measured 15°/hour rotation, as documented in 'Behind the Curve.'"],
    unresolved: ["Why belief revived so effectively in the 2010s—the sociology and algorithm question, not the shape question.", "How best to communicate with believers for whom the claim anchors community and distrust of institutions.", "Nothing about the Earth's shape is unresolved."],
    timeline: [
      { date: "c. 240 BCE", event: "Eratosthenes measures Earth's circumference using shadows at Syene and Alexandria.", status: "Confirmed" },
      { date: "1519–1522", event: "The Magellan–Elcano expedition circumnavigates the globe.", status: "Confirmed" },
      { date: "1849", event: "Rowbotham's Bedford Level experiment founds modern flat-earth belief; controlled repeats later confirm curvature.", status: "Confirmed" },
      { date: "1946–1972", event: "Rocket and Apollo photography images the full disc of Earth from space.", status: "Confirmed" },
      { date: "c. 2014", event: "Video recommendation algorithms revive flat-earth belief into a global subculture.", status: "Confirmed" },
      { date: "2018", event: "'Behind the Curve' documents believers' own gyroscope measuring Earth's 15°/hour rotation.", status: "Confirmed" },
      { date: "Today", event: "DSCOVR/EPIC photographs the full sunlit disc from 1.5 million km, many times daily, publicly.", status: "Confirmed" }
    ],
    evidenceCards: [
      { title: "The horizon test", theory: "The horizon looks flat, rises to eye level at altitude, and distant objects hidden by 'curvature math' can sometimes be seen again with zoom.", record: "Ships vanish hull-first and zoom never retrieves the hull; the horizon drops measurably below eye level at altitude (visible with a $30 theodolite app); and the occasional long-distance sighting is well-documented atmospheric refraction—the same effect that failed Rowbotham's canal experiment when controls were added.", sourceIds: ["fe-eratosthenes"] },
      { title: "The southern sky", theory: "Star trails prove nothing—the whole sky could rotate above the disc like a planetarium dome.", record: "A dome cannot give Sydney, Santiago, and Cape Town the same southern stars rotating clockwise around one southern pole while the north sees the opposite. Two hemispheres of counter-rotating sky is spherical geometry, observable with a camera and a tripod.", sourceIds: ["fe-eratosthenes"] },
      { title: "Flights and maps", theory: "Airline routes are distorted by projection tricks, and no one can really check the southern ones.", record: "Anyone can check: Sydney–Santiago, Perth–Johannesburg, and Auckland–Buenos Aires fly daily in ~11–13 hours. On every published flat map those routes span the disc's widest stretches—requiring supersonic airliners. No flat map preserving real distances has ever been produced; on a globe, one does automatically.", sourceIds: ["fe-gps"] },
      { title: "The photos from space", theory: "Every 'blue marble' is a NASA composite or CGI—they've admitted assembling images.", record: "Some published images are mosaics, openly labelled. But DSCOVR/EPIC publishes full-disc photographs many times daily from 1.5 million km; other nations' space agencies (rivals with no reason to protect NASA) produce matching imagery; and high-altitude balloon footage with non-fisheye lenses shows the curve.", sourceIds: ["fe-epic"] },
      { title: "Their own instruments", theory: "Honest independent experiments will expose the fraud—that's why believers fund gyroscope and laser tests.", record: "They did fund them. The $20,000 ring-laser gyroscope measured 15°/hour drift—Earth's rotation. The laser-through-fences test showed the light rising relative to the surface—curvature. Both results, filmed for 'Behind the Curve,' were rejected by the experimenters. The record won the experiments; the theory kept the believers.", sourceIds: ["fe-gps", "fe-epic"] }
    ],
    sources: [
      { id: "fe-eratosthenes", title: "Eratosthenes", publisher: "Encyclopaedia Britannica", type: "Historical reference", url: "https://www.britannica.com/biography/Eratosthenes" },
      { id: "fe-epic", title: "DSCOVR: EPIC — Earth Polychromatic Imaging Camera", publisher: "NASA Goddard", type: "Live full-disc imagery", url: "https://epic.gsfc.nasa.gov/" },
      { id: "fe-gps", title: "GPS: The Global Positioning System", publisher: "U.S. Government / GPS.gov", type: "Operational system documentation", url: "https://www.gps.gov/systems/gps/" },
      { id: "fe-iss", title: "International Space Station", publisher: "NASA", type: "Continuous orbital platform", url: "https://www.nasa.gov/international-space-station/" }
    ]
  },
  {
    slug: "jfk", title: "JFK Assassination", question: "Did Lee Harvey Oswald act alone?",
    hook: "Six seconds in Dealey Plaza produced the most investigated murder in American history—and sixty years of argument about what the investigators missed.",
    category: "Historical events", reviewed: "July 2026",
    conventional: "The Warren Commission concluded that Lee Harvey Oswald fired three shots from the sixth floor of the Texas School Book Depository, killing President Kennedy and wounding Governor Connally, and found no credible evidence that Oswald or Jack Ruby was part of a conspiracy.",
    alternative: "Critics point to a rushed first investigation, disputed medical and witness evidence, decades of CIA and FBI secrecy about what they knew of Oswald, and the House committee's 1979 acoustic finding of a probable second gunman.",
    readTime: "22 min",
    overview: "President John F. Kennedy was shot in Dallas on 22 November 1963. Oswald was arrested that afternoon and killed by Jack Ruby two days later, so no trial ever tested the evidence. Two major federal inquiries agreed Oswald fired the shots but split on whether anyone else was involved. The surviving record is enormous—millions of pages—and still growing: more than 80,000 pages were declassified in March 2025 alone.",
    story: [
      { heading: "Six seconds in Dealey Plaza", body: [
        "At 12:30 p.m. on 22 November 1963, the presidential motorcade turned from Houston Street onto Elm, passing directly beneath the Texas School Book Depository. Shots struck President Kennedy and Texas Governor John Connally. Kennedy was pronounced dead at Parkland Hospital about half an hour later.",
        "Within 45 minutes, Dallas patrolman J. D. Tippit was shot dead in the Oak Cliff neighborhood. Police arrested Lee Harvey Oswald—a 24-year-old Depository employee, ex-Marine, and one-time defector to the Soviet Union—in a movie theatre shortly afterward. He denied everything, calling himself 'a patsy.'",
        "He never got the chance to say more. On 24 November, as Oswald was being transferred through the basement of Dallas police headquarters on live television, nightclub owner Jack Ruby stepped out of the crowd and shot him. The one person who knew exactly what happened was dead, and the vacuum he left has been filled with theories ever since." ] },
      { heading: "The official answer, twice", body: [
        "The Warren Commission, appointed within a week of the assassination, reported in September 1964: Oswald fired three shots from the sixth-floor corner window, acting alone, and Ruby also acted alone. Its evidence base was substantial—the recovered Mannlicher–Carcano rifle mail-ordered under Oswald's alias, cartridge cases at the window, ballistics matches, fibers, eyewitnesses, and Oswald's palm print on the rifle barrel.",
        "Fifteen years later, the House Select Committee on Assassinations reheard the case with better forensics. It agreed on the essentials—Oswald fired the shots that killed Kennedy—but then, relying heavily on an acoustic analysis of a police dictabelt recording, concluded there was 'probably' a fourth shot from the grassy knoll, and therefore probably a conspiracy. It could not say who the second gunman was.",
        "That acoustic finding was attacked almost immediately. A National Academy of Sciences panel concluded in 1982 that the impulses on the recording were likely made about a minute after the shooting, and the identification remains heavily disputed. The strange result: the U.S. government's last official word both confirms Oswald as the shooter and gestures at a conspiracy it cannot describe." ] },
      { heading: "What the agencies didn't say", body: [
        "The strongest fuel for doubt has never been a rival gunman—it is what the intelligence agencies concealed. The CIA did not tell the Warren Commission it had been plotting with the Mafia to kill Fidel Castro, an obvious motive question. The FBI destroyed a note Oswald had left at its Dallas office days before the assassination. The CIA monitored Oswald's visit to the Soviet and Cuban embassies in Mexico City weeks before Dallas and was later found to have run a deliberately 'benign cover-up' of what it knew.",
        "The Assassination Records Review Board, created after the film JFK reignited public anger, spent the 1990s forcing millions of pages into the open and documented these failures in detail. Its conclusion was pointed: the secrecy itself, more than any evidence, convinced the public that the government had something to hide.",
        "In March 2025, following an executive order, the National Archives released more than 80,000 additional pages in one of the largest single declassifications in U.S. history. Researchers found new detail on CIA surveillance of Oswald in Mexico City, the Castro plots, and Kennedy's own friction with the agency—context that deepens the story of institutional secrecy without identifying any second shooter." ] },
      { heading: "Where the case actually stands", body: [
        "Strip the case to its physical core and it is hard to move: Oswald's rifle, fired from Oswald's workplace, with Oswald fleeing and killing a policeman before arrest. Polls have long shown most Americans believe in a conspiracy, but sixty years of investigation—official, journalistic, and amateur—have not produced a confessed accomplice, a documented payment, or a second weapon.",
        "What the record does support is a narrower, well-documented scandal: agencies that knew far more about Oswald than they admitted, and protected themselves at the cost of public trust. Whether that concealment hid mere incompetence or something worse is the question the files keep almost answering." ] }
    ],
    sharedFacts: ["Kennedy and Connally were struck while the motorcade passed the Depository at 12:30 p.m.", "Oswald worked in the building and left within minutes of the shooting.", "A Mannlicher–Carcano rifle ordered under Oswald's alias was recovered on the sixth floor with three cartridge cases.", "Officer J. D. Tippit was killed about 45 minutes later; Oswald was arrested nearby.", "Jack Ruby killed Oswald in police custody on 24 November 1963, before any trial."],
    unresolved: ["Why the CIA and FBI concealed their pre-assassination knowledge of Oswald, and whether anything material is still withheld.", "How to weigh witness recollections of shots from the grassy knoll against the physical evidence.", "Whether Ruby's silencing of Oswald was impulse, as investigators concluded, or something arranged.", "What, if anything, remains in the still-unreleased portion of the collection."],
    timeline: [
      { date: "22 Nov 1963", event: "Kennedy is shot at 12:30 p.m.; Tippit is killed; Oswald is arrested at the Texas Theatre.", status: "Confirmed" },
      { date: "24 Nov 1963", event: "Jack Ruby shoots Oswald during a live televised jail transfer.", status: "Confirmed" },
      { date: "24 Sep 1964", event: "The Warren Commission reports that Oswald acted alone.", status: "Confirmed" },
      { date: "1979", event: "The House Select Committee finds a 'probable conspiracy,' relying heavily on disputed acoustic evidence.", status: "Reported" },
      { date: "1982", event: "A National Academy of Sciences panel rejects the acoustic second-shot analysis.", status: "Confirmed" },
      { date: "1992–1998", event: "The Assassination Records Review Board forces millions of pages into the open and documents agency concealment.", status: "Confirmed" },
      { date: "23 Jan 2025", event: "Executive Order 14176 orders full declassification of remaining JFK records.", status: "Confirmed" },
      { date: "18 Mar 2025", event: "The National Archives releases more than 80,000 pages; researchers find new Mexico City surveillance detail but no second shooter.", status: "Confirmed" }
    ],
    evidenceCards: [
      { title: "The murder weapon", theory: "The 'magic bullet' path is impossible, the evidence was mishandled, and a planted rifle can't prove who fired.", record: "The Carcano traced to Oswald's mail-order alias, his palm print on the barrel, three cartridge cases at the window, and ballistics matches tie weapon and shooter together. No rival weapon has ever been produced.", sourceIds: ["jfk-wc"] },
      { title: "Oswald's next 45 minutes", theory: "A patsy fleeing a frame-up would look exactly like a guilty man fleeing a crime—flight proves fear, not murder.", record: "Oswald left the building within minutes, retrieved a pistol, killed Officer Tippit before multiple eyewitnesses, and resisted arrest. Conduct isn't proof of the first shooting, but it fits one story far better than the other.", sourceIds: ["jfk-wc", "jfk-nara"] },
      { title: "The second-gunman recording", theory: "The House committee's own experts found a fourth shot from the grassy knoll on a police dictabelt—an official finding of conspiracy.", record: "A National Academy of Sciences panel showed the impulses were likely recorded about a minute after the shooting. The acoustic case has never recovered scientific standing.", sourceIds: ["jfk-hsca"] },
      { title: "What the agencies hid", theory: "The CIA concealed the Castro plots and its Oswald surveillance; the FBI destroyed evidence. Innocent institutions don't behave that way.", record: "The concealment is real and documented—but three decades of forced disclosure, including 80,000 pages in 2025, have produced no document identifying a second shooter or an operational plot.", sourceIds: ["jfk-arrb", "jfk-2025"] },
      { title: "The grassy knoll witnesses", theory: "Dozens of people in Dealey Plaza reported shots or smoke from the knoll; some Parkland doctors described wounds implying a frontal shot.", record: "Accounts conflict with each other and with the physical evidence; the autopsy materials, despite handling failures, support shots from above and behind. Crowd memory under gunfire is demonstrably unreliable.", sourceIds: ["jfk-wc", "jfk-arrb"] }
    ],
    sources: [
      { id: "jfk-wc", title: "Report of the President's Commission on the Assassination of President Kennedy", publisher: "U.S. National Archives", type: "Official investigation", url: "https://www.archives.gov/research/jfk/warren-commission-report" },
      { id: "jfk-hsca", title: "House Select Committee on Assassinations report", publisher: "U.S. National Archives", type: "Congressional investigation", url: "https://www.archives.gov/research/jfk/select-committee-report" },
      { id: "jfk-arrb", title: "Assassination Records Review Board final report", publisher: "U.S. National Archives", type: "Official review", url: "https://www.archives.gov/files/research/jfk/review-board/report/arrb-final-report.pdf" },
      { id: "jfk-nara", title: "Warren Commission records introduction", publisher: "U.S. National Archives", type: "Archive guide", url: "https://www.archives.gov/research/jfk/warren-commission-report/intro" },
      { id: "jfk-2025", title: "JFK Assassination Records—2025 release", publisher: "U.S. National Archives", type: "Primary document collection", url: "https://www.archives.gov/research/jfk/release-2025" }
    ]
  },
  {
    slug: "mh370", title: "Malaysia Airlines MH370", question: "What caused the aircraft to disappear?",
    hook: "A Boeing 777 with 239 people aboard flew silently for seven hours after saying goodnight—and after four seabed searches, the ocean still hasn't given it back.",
    category: "Missing persons & transport", reviewed: "July 2026",
    conventional: "Radar, satellite handshakes, fuel modelling, and recovered debris indicate the Boeing 777 reversed course, flew south for hours, and ended in the southern Indian Ocean after fuel exhaustion. The official investigation could not determine who diverted it or why.",
    alternative: "Competing scenarios include deliberate pilot action, hijacking, fire, depressurization, interception, and proposed crash locations outside the searched zones. Some fit portions of the data; none explains the complete record conclusively.",
    readTime: "24 min",
    overview: "MH370 left Kuala Lumpur for Beijing with 239 people aboard just after midnight on 8 March 2014. Its transponder stopped, military radar tracked it doubling back across Malaysia, and its satellite terminal kept exchanging automated signals for nearly seven more hours. Debris later washed up across the western Indian Ocean, but four major seabed searches—the latest concluding without findings in early 2026—have not located the wreckage or the flight recorders.",
    story: [
      { heading: "Goodnight, Malaysian three-seven-zero", body: [
        "At 12:42 a.m. on 8 March 2014, MH370 lifted off from Kuala Lumpur bound for Beijing: 227 passengers, 12 crew, a veteran captain with over 18,000 flight hours. At 1:19 a.m., as the aircraft crossed from Malaysian to Vietnamese airspace, the captain signed off with air traffic control: 'Good night, Malaysian three seven zero.'",
        "Two minutes later the transponder stopped transmitting. The aircraft vanished from civilian radar at the precise seam between two countries' control zones—the moment when neither is quite watching. Vietnamese controllers waited; Malaysian controllers assumed a handoff. Hours passed before anyone declared an emergency.",
        "Military radar later showed what civilian screens could not: the 777 had banked hard around, recrossed the Malay Peninsula, and flown northwest up the Strait of Malacca before passing out of radar range. Someone, or something, had turned the aircraft around—with its communications dark." ] },
      { heading: "Seven hours of handshakes", body: [
        "The aircraft's satellite terminal, though silenced for messaging, kept answering automated hourly 'handshakes' from an Inmarsat satellite. Engineers realized these pings encoded two measurable quantities: signal travel time, which places the aircraft on rings of distance from the satellite, and frequency shift, which hints at speed and direction.",
        "The analysis, checked against other flights, pointed one way: after leaving radar coverage the aircraft flew a long, steady track south into the empty southern Indian Ocean. The final, incomplete handshake at 8:19 a.m.—consistent with electrical interruption at fuel exhaustion—defined the now-famous '7th arc,' the line along which the flight ended.",
        "It remains one of the most remarkable pieces of forensic engineering in aviation history—and one of its cruelest results, because the arc is thousands of kilometres long, crossing some of the deepest, least-mapped seabed on Earth." ] },
      { heading: "The ocean gives back pieces", body: [
        "For over a year there was no physical trace, and rival theories flourished: the plane was in Kazakhstan, in Diego Garcia, shot down, never crashed at all. Then in July 2015 a barnacle-encrusted flaperon washed onto a beach on Réunion Island, 4,000 km from the search zone. Serial numbers confirmed it: MH370.",
        "More than 30 pieces of debris followed on the shores of Madagascar, Mozambique, Tanzania, and South Africa—several confirmed, others assessed as almost certainly from the aircraft. Drift modelling worked backwards from the finds and pointed, again, to the southern Indian Ocean along the 7th arc. Damage analysis of the flap and flaperon suggested the aircraft was not configured for a controlled ditching.",
        "The debris demolished the landing theories but could not answer the harder question. Australia's 120,000 km² sonar search ended empty in 2017. Ocean Infinity's 2018 no-find-no-fee search also came up empty. Malaysia's 2018 safety report was blunt: the team was 'unable to determine the real cause for the disappearance.'" ] },
      { heading: "The pilot question and the 2026 search", body: [
        "The most discussed scenario is also the darkest: deliberate diversion by someone in the cockpit. The turn-back was flown skillfully, communications ceased in a suspicious sequence, and a flight-simulator recovered from the captain's home contained a deleted session tracing a route into the southern Indian Ocean. Malaysian investigators noted it but found no motive, no warning signs, and no evidence conclusive enough to name anyone. Pilot associations and family members object that the case is circumstantial—and alternative scenarios, like a hypoxia event after a failed emergency, have never been fully excluded.",
        "In 2025 Malaysia signed a new no-find-no-fee agreement with Ocean Infinity, whose robotic fleet returned to the 7th arc. After a weather pause, the search ran from 30 December 2025 to 23 January 2026, covering targeted areas identified by a decade of refined drift and signal analysis. In March 2026 the company announced the campaign had concluded without findings.",
        "Each empty search shrinks the credible zone. The wreckage is almost certainly down there, in water up to 6,000 metres deep, holding the two recorders that could finally separate the deliberate from the tragic. Until a search vehicle passes over the right patch of seabed, MH370 remains aviation's defining unsolved case." ] }
    ],
    sharedFacts: ["The aircraft stopped normal transmissions minutes after the final radio call at the Malaysia–Vietnam airspace boundary.", "Military radar tracked a turn back across the Malay Peninsula and up the Strait of Malacca.", "The satellite terminal exchanged automated signals until 00:19 UTC, about seven hours after takeoff.", "A flaperon found on Réunion in 2015 was confirmed as MH370; many further pieces were confirmed or assessed as almost certain.", "Four major underwater searches (2014–17, 2018, and 2025–26) have not located the main wreckage."],
    unresolved: ["Who changed the aircraft's course, and whether the diversion was deliberate.", "The exact endpoint along the 7th arc, after roughly 200,000 km² of seabed searched.", "What happened aboard during the final hours—control inputs, cabin state, and whether anyone was conscious at the end.", "Whether the remaining unsearched arc segments will be covered before the case goes cold."],
    timeline: [
      { date: "8 Mar 2014", event: "MH370 departs Kuala Lumpur at 12:42 a.m.; last radio call 1:19 a.m.; transponder stops; military radar tracks a westward turn.", status: "Confirmed" },
      { date: "24 Mar 2014", event: "Malaysia announces satellite analysis places the flight's end in the southern Indian Ocean.", status: "Reported" },
      { date: "29 Jul 2015", event: "A flaperon found on Réunion Island is later confirmed as MH370 debris.", status: "Confirmed" },
      { date: "17 Jan 2017", event: "The 120,000 km² Australian-led underwater search is suspended without success.", status: "Confirmed" },
      { date: "May 2018", event: "Ocean Infinity's first no-find-no-fee search ends empty after covering a further ~112,000 km².", status: "Confirmed" },
      { date: "30 Jul 2018", event: "Malaysia's safety investigation report is released without determining the cause.", status: "Confirmed" },
      { date: "25 Feb 2025", event: "Malaysia approves a new Ocean Infinity search under a no-find-no-fee agreement.", status: "Confirmed" },
      { date: "30 Dec 2025 – 23 Jan 2026", event: "Ocean Infinity conducts a targeted 7th-arc search; in March 2026 it announces the campaign concluded without findings.", status: "Confirmed" }
    ],
    evidenceCards: [
      { title: "Where the flight ended", theory: "The satellite math is unproven inference—the plane could have flown north, landed, or been taken. No wreck, no proof.", record: "Inmarsat timing and frequency data, checked against other flights, constrain a long southbound track ending at fuel exhaustion near the 7th arc. Independent fuel and performance models agree.", sourceIds: ["mh-atsb"] },
      { title: "The debris on the beaches", theory: "Pieces appearing years later, found by chance on distant shores, could be planted or misidentified.", record: "The Réunion flaperon carries serial-numbered parts matched to MH370's build records; 30+ further pieces washed up exactly where drift models predict from a southern-arc crash. Damage suggests a high-energy impact, not a gentle ditching.", sourceIds: ["mh-debris", "mh-atsb"] },
      { title: "Who turned the plane", theory: "The captain did it: the turn-back threaded radar blind spots, communications died in sequence, and his home simulator held a deleted route into the southern Indian Ocean.", record: "The diversion pattern does suggest skilled control inputs—but no motive, note, or claim was ever found, investigators declined to name anyone, and hypoxia or emergency scenarios were never conclusively excluded. Without the recorders, this stays open.", sourceIds: ["mh-malaysia"] },
      { title: "Four empty searches", theory: "~200,000 km² of seabed searched and nothing found—the endpoint models must be wrong, perhaps a piloted glide far beyond the arc.", record: "The failed searches genuinely weaken confidence in the precise endpoint—while still excluding only part of the plausible zone. A miss in deep, unmapped ocean does not overturn the satellite and debris evidence.", sourceIds: ["mh-atsb", "mh-oi2026"] },
      { title: "The exotic endings", theory: "Shoot-down, remote hijack, a northern route to Kazakhstan, a secret landing—books and documentaries keep the alternatives alive.", record: "Each requires discarding the satellite data, the confirmed debris, or both. Twelve years on, none has produced a single piece of physical evidence.", sourceIds: ["mh-atsb", "mh-debris"] }
    ],
    sources: [
      { id: "mh-atsb", title: "The Operational Search for MH370", publisher: "Australian Transport Safety Bureau", type: "Official search report", url: "https://www.atsb.gov.au/sites/default/files/media/5773565/operational-search-for-mh370_final_3oct2017.pdf" },
      { id: "mh-debris", title: "MH370—Search and debris examination update", publisher: "Australian Transport Safety Bureau", type: "Official technical report", url: "https://www.atsb.gov.au/sites/default/files/media/5773389/ae-2014-054_mh370-search-and-debris-update_aug2017.pdf" },
      { id: "mh-malaysia", title: "MH370 Safety Investigation Report release", publisher: "Malaysia Ministry of Transport", type: "Official investigation", url: "https://www.mot.gov.my/en/Kenyataan%20Media/Year%202018/YBMOT%20Media%20Statement%20MH370%20Safety%20Investigation%20Report.pdf" },
      { id: "mh-oi2026", title: "Conclusion of the search for Malaysian Airlines flight MH370", publisher: "Ocean Infinity", type: "Search operator statement", url: "https://oceaninfinity.com/news/conclusion-of-the-search-for-malaysian-airlines-flight-mh370/" },
      { id: "mh-reports", title: "MH370 operational search reports", publisher: "Australian Transport Safety Bureau", type: "Report collection", url: "https://www.atsb.gov.au/mh370-operational-search-reports" }
    ]
  },
  {
    slug: "moon", title: "The Moon Landing", question: "Did Apollo 11 land on the Moon?",
    hook: "Half a billion people watched it live. Decades later, lasers still bounce off hardware the astronauts left behind—yet the hoax theory refuses to die.",
    category: "Space & UFOs", reviewed: "July 2026",
    conventional: "Apollo 11 landed astronauts on the Moon in July 1969. The record is supported by telemetry tracked worldwide, 382 kg of returned samples studied internationally, surface experiments, retroreflectors still in use, and modern orbital photographs of the hardware and astronaut tracks.",
    alternative: "Hoax claims interpret photographic lighting, the 'waving' flag, radiation exposure, and the starless sky as evidence of staging. Each observation has an ordinary photographic, mechanical, or mission-design explanation.",
    readTime: "16 min",
    overview: "Apollo 11 launched on 16 July 1969. Neil Armstrong and Buzz Aldrin landed the lunar module Eagle in the Sea of Tranquility while Michael Collins orbited above. Five more Apollo crews landed through 1972. The evidence is not one grainy broadcast: it is physical material, working instruments, independent tracking by rival nations, and photographs taken from lunar orbit within the last two decades. In April 2026, Artemis II carried four astronauts around the Moon—the first crewed lunar flight since Apollo.",
    story: [
      { heading: "The thing itself", body: [
        "On 20 July 1969, the lunar module Eagle touched down with well under a minute of landing fuel remaining, Armstrong flying manually past a boulder field. Six hours later he stepped onto the surface before a live television audience estimated at 600 million—at the time, the largest in history.",
        "Apollo 11 was not a stunt performed in isolation. It was the endpoint of eight years of incremental, publicly tracked missions—Mercury, Gemini, the Apollo test flights—involving some 400,000 workers. Six landings followed through 1972; twelve people walked on the Moon and returned 382 kilograms of rock and soil.",
        "Crucially, the United States' chief rival watched everything. The Soviet Union, with every incentive to expose a fraud and the radio telescopes to do it, tracked the missions and never disputed them—because its own instruments confirmed where the signals were coming from." ] },
      { heading: "Where the hoax story came from", body: [
        "Doubt was born almost immediately but crystallized in 1976 with a self-published book, 'We Never Went to the Moon,' and grew through the post-Watergate collapse of trust in government. A 2001 television special introduced the claims to a new generation, and internet video later gave them permanent life.",
        "The arguments have barely changed in fifty years: the flag appears to wave in vacuum; the photographs show no stars; shadows fall at odd angles; the Van Allen radiation belts should have been lethal; the footage looks like a soundstage—perhaps Stanley Kubrick's.",
        "Each has a plain answer. The flag swings because a horizontal rod holds it out and nothing damps its motion in vacuum. Stars are absent because the surface is daylight-bright and the cameras exposed for it. Shadows diverge because of perspective and uneven terrain. The crews crossed the radiation belts in hours, receiving doses comparable to a CT scan. And the 'perfect studio' of 1969 would have needed video technology—slow-motion at broadcast length, wireless handheld cameras behaving in one-sixth gravity—that did not exist.",
        "The deeper problem is scale: a fake would have required hundreds of thousands of people, six times over, to keep a perfect secret for decades while the Soviet Union listened in." ] },
      { heading: "Evidence you can check today", body: [
        "The Apollo record is unusual among historical events: it is still generating fresh, independent confirmation. Since 2009 NASA's Lunar Reconnaissance Orbiter has photographed every Apollo site from orbit, resolving descent stages, experiment packages, and the dark lines of astronaut footpaths. Independent lunar orbiters from other nations have imaged disturbance at the sites.",
        "Observatories on Earth routinely fire lasers at the retroreflector arrays Apollo 11, 14, and 15 left on the surface, measuring the Earth–Moon distance to millimetres—an experiment running continuously for over five decades. The returned samples, distributed to laboratories worldwide, show isotope chemistry and micrometeorite weathering that could not have been synthesized in 1969 and that later robotic missions corroborated.",
        "In April 2026, Artemis II carried four astronauts on a ten-day flight around the Moon—the first crewed lunar voyage in more than fifty years, and a reminder of how enormous an undertaking even a flyby remains." ] }
    ],
    sharedFacts: ["Apollo 11 launched on a Saturn V on 16 July 1969 and returned three astronauts safely on 24 July.", "The mission broadcast live television and radio received by stations in multiple countries.", "382 kg of lunar material from six landings was distributed to researchers worldwide.", "Retroreflectors at three Apollo sites are still used for laser ranging.", "Lunar Reconnaissance Orbiter images show hardware and tracks at all six landing sites."],
    unresolved: ["Minor discrepancies in mission recollections and archival labelling, typical of any large historical record.", "How to preserve the landing sites as new missions and commercial landers reach the Moon.", "None of the open questions materially challenges whether the landings occurred."],
    timeline: [
      { date: "16 Jul 1969", event: "Apollo 11 launches from Kennedy Space Center before a million spectators.", status: "Confirmed" },
      { date: "20 Jul 1969", event: "Eagle lands in the Sea of Tranquility; Armstrong and Aldrin walk on the surface.", status: "Confirmed" },
      { date: "24 Jul 1969", event: "The crew splashes down in the Pacific with the first lunar samples.", status: "Confirmed" },
      { date: "1969–1972", event: "Five further Apollo crews land; Apollo 13 aborts and returns safely.", status: "Confirmed" },
      { date: "1976", event: "The modern hoax narrative begins with Bill Kaysing's self-published book.", status: "Confirmed" },
      { date: "2009", event: "Lunar Reconnaissance Orbiter begins imaging Apollo hardware and astronaut tracks.", status: "Confirmed" },
      { date: "2023–2024", event: "Spacecraft-based laser ranging measures Apollo reflector arrays anew.", status: "Confirmed" },
      { date: "1–10 Apr 2026", event: "Artemis II carries four astronauts around the Moon—the first crewed lunar flight since Apollo.", status: "Confirmed" }
    ],
    evidenceCards: [
      { title: "The rocks", theory: "The 'moon rocks' were collected by robots or faked from meteorites in a lab.", record: "382 kg of material shows isotope ratios, cosmic-ray exposure, and micrometeorite weathering only long lunar residence produces—verified by laboratories worldwide and corroborated by later robotic sample returns. No 1969 lab could fake it, and no robot could collect that much.", sourceIds: ["moon-apollo"] },
      { title: "The Soviets were listening", theory: "NASA controlled the broadcast, so NASA controlled the story.", record: "Tracking stations in multiple countries—including the USSR, with every incentive and instrument to expose a fraud—followed the telemetry from translunar space and confirmed where the signals came from. The rival superpower never disputed the landings.", sourceIds: ["moon-apollo"] },
      { title: "Photos of the sites today", theory: "All imagery of the landing sites comes from NASA, so it proves nothing.", record: "LRO has photographed descent stages, experiments, and boot-track trails at all six sites since 2009—matching maps drawn four decades earlier—and non-NASA orbiters have independently imaged site disturbance.", sourceIds: ["moon-lro"] },
      { title: "The mirrors still work", theory: "Reflectors could have been placed by robots, like the Soviet Lunokhod arrays.", record: "True as far as it goes—but the arrays sit precisely where the mission records place them, and they anchor a 50-year ranging experiment any equipped observatory can repeat tonight. The hoax must now include working hardware at six sites.", sourceIds: ["moon-laser", "moon-orbit"] },
      { title: "The 'studio' anomalies", theory: "Waving flag, no stars, crooked shadows, crosshairs behind objects—the footage looks staged.", record: "Undamped flag motion in vacuum, daylight exposure settings, perspective on uneven terrain, and photo-emulsion bleed explain every item; and faking the footage would have required video technology that did not exist in 1969.", sourceIds: ["moon-apollo"] }
    ],
    sources: [
      { id: "moon-apollo", title: "Apollo 11 Mission Overview", publisher: "NASA", type: "Mission record", url: "https://www.nasa.gov/history/apollo-11-mission-overview/" },
      { id: "moon-lro", title: "Apollo 11 Landing Site", publisher: "NASA Earth Observatory", type: "Orbital imagery", url: "https://science.nasa.gov/earth/earth-observatory/apollo-11-landing-site-39408/" },
      { id: "moon-laser", title: "Apollo and Luna reflectors", publisher: "International Laser Ranging Service / NASA GSFC", type: "Scientific instrument record", url: "https://ilrs.gsfc.nasa.gov/missions/satellite_missions/current_missions/ap11_general.html" },
      { id: "moon-orbit", title: "First spacecraft-based laser ranging to lunar surface reflectors", publisher: "NASA Goddard", type: "Scientific dataset summary", url: "https://pgda.gsfc.nasa.gov/products/100" },
      { id: "moon-artemis", title: "Artemis II: NASA's First Crewed Lunar Flyby in 50 Years", publisher: "NASA", type: "Mission record", url: "https://www.nasa.gov/mission/artemis-ii/" }
    ]
  },
  {
    slug: "roswell", title: "Roswell", question: "What crashed near Roswell in 1947?",
    hook: "The Army announced a captured 'flying disc,' retracted it within hours, and spent fifty years explaining the retraction. The debris was real—the argument is about what it was.",
    category: "Space & UFOs", reviewed: "July 2026",
    conventional: "The debris most likely came from a Project MOGUL balloon train—a classified program listening for Soviet nuclear tests. Secrecy around MOGUL's purpose produced the contradictory public explanations that fed suspicion for decades.",
    alternative: "Witnesses and later accounts describe unusual material, aggressive military retrieval, and—in stories emerging decades later—bodies or a non-human craft. Advocates argue the balloon explanations were themselves the cover story.",
    readTime: "18 min",
    overview: "In summer 1947, rancher W. W. 'Mac' Brazel found scattered lightweight debris northwest of Roswell, New Mexico. On 8 July the local Army airfield announced it had recovered a 'flying disc'—then higher command displayed weather-balloon wreckage and the story died for thirty years. Revived in 1978 by new interviews, Roswell became the world's most famous UFO story. Official inquiries in the 1990s tied the debris to the then-classified MOGUL program.",
    story: [
      { heading: "A rancher, a press release, a retraction", body: [
        "Sometime in June or early July 1947—weeks after pilot Kenneth Arnold's 'flying saucer' sighting had set off a national craze—Mac Brazel collected a field of odd debris on the Foster ranch: foil, rubber strips, sticks, and paper-backed tape with faint floral figures. He mentioned it in town; the sheriff called the airfield.",
        "On 8 July 1947, the Roswell Army Air Field public information office issued one of the most consequential press releases ever written: the Army had recovered a 'flying disc.' Newspapers worldwide ran it. Within hours, Eighth Air Force commander General Roger Ramey held a press conference in Fort Worth displaying torn balloon wreckage: it was a weather balloon and radar target. The papers ran the correction, and Roswell went quiet for thirty-one years.",
        "The speed and clumsiness of that reversal is the seed of everything that followed. Both things cannot be fully true—either the intelligence officers of the only atomic-bomb unit in the world couldn't recognize a weather balloon, or the balloon story was covering something." ] },
      { heading: "The thirty-year silence breaks", body: [
        "In 1978, ufologist Stanton Friedman interviewed Jesse Marcel, the intelligence officer who had collected the 1947 debris. Marcel said the material was 'not of this earth'—thin, light, extraordinarily strong, unlike anything he knew. The 1980 book 'The Roswell Incident' built the modern narrative, and through the 1980s and 90s new witnesses added military cordons, threats, debris flown out on secret flights—and, eventually, small non-human bodies and a second crash site.",
        "By the fiftieth anniversary in 1997, polls showed most Americans believed something extraterrestrial had crashed at Roswell. The story had grown from a debris field to a full recovery operation with autopsies—almost entirely on testimony recorded decades after the event, some of it secondhand, some later recanted or discredited.",
        "Memory research offers a caution here: fifty-year-old recollections, retold under intense publicity and suggestion, are unreliable in well-documented ways. That does not make witnesses liars; it makes late testimony weak evidence." ] },
      { heading: "MOGUL steps out of the vault", body: [
        "In 1994, under congressional pressure, the Air Force searched its classified records and published an answer: the debris matched Project MOGUL, a top-secret experiment flying trains of balloons and radar reflectors from Alamogordo, designed to detect sound waves from anticipated Soviet nuclear tests. MOGUL Flight 4, launched in early June 1947, was never recovered and was projected toward the Foster ranch area.",
        "The details clicked into place: the foil and sticks match radar reflectors; the flowered tape matches reflectors assembled by a toy company using festive tape; the secrecy was real—MOGUL's purpose was among the most sensitive of the early Cold War, worth protecting even with an awkward cover story.",
        "A 1997 follow-up report, 'Case Closed,' addressed the body accounts, attributing them to conflated memories of 1950s parachute-test dummies and a 1956 aircraft accident. Skeptics of the official account note the time-compression argument cuts both ways, and that no launch log survives for Flight 4—a genuine gap. But no physical evidence of anything non-human has ever surfaced, and the documentary trail for MOGUL is thick." ] }
    ],
    sharedFacts: ["Debris was collected from the Foster ranch northwest of Roswell in summer 1947.", "The Army announced a recovered 'flying disc' on 8 July 1947 and retracted it within hours.", "Classified balloon trains with radar reflectors were flying from Alamogordo that June under Project MOGUL.", "The extraterrestrial narrative emerged publicly after 1978; body claims came later still.", "No physical sample of the debris is publicly available for testing."],
    unresolved: ["Why the initial press release said 'flying disc'—enthusiasm, confusion, or something else.", "Which exact MOGUL flight produced the debris, since Flight 4's launch log did not survive.", "How much of the later testimony reflects real 1947 memories versus publicity-shaped reconstruction.", "Whether any 1947-era records remain unlocated."],
    timeline: [
      { date: "24 Jun 1947", event: "Kenneth Arnold's sighting launches the national 'flying saucer' craze.", status: "Confirmed" },
      { date: "Jun–Jul 1947", event: "Brazel finds a wide field of lightweight debris on the Foster ranch.", status: "Reported" },
      { date: "8 Jul 1947", event: "Roswell AAF announces a 'flying disc'; General Ramey displays balloon wreckage the same day.", status: "Confirmed" },
      { date: "1978", event: "Jesse Marcel's interviews revive the story as an extraterrestrial crash.", status: "Reported" },
      { date: "1980–1995", event: "Books and new witnesses add cordons, secret flights, bodies, and a second site.", status: "Disputed" },
      { date: "1994", event: "The Air Force's records search concludes the debris was consistent with Project MOGUL.", status: "Confirmed" },
      { date: "1997", event: "'Case Closed' attributes body accounts to 1950s dummy tests and accidents.", status: "Confirmed" }
    ],
    evidenceCards: [
      { title: "What the debris was", theory: "The materials were like nothing on Earth—foil that unfolded itself, symbols no one recognized. A balloon doesn't warrant an armed retrieval.", record: "Declassified MOGUL records document balloon trains with radar reflectors—foil, balsa sticks, and toy-company tape with floral figures—flying from Alamogordo that June, one flight unrecovered and projected toward the ranch. Contemporaneous 1947 descriptions match those mundane materials.", sourceIds: ["roswell-af", "roswell-report"] },
      { title: "The retracted press release", theory: "The atomic-bomb unit's own intelligence officers announced a 'flying disc,' then higher command killed the story in hours. That's a cover-up, documented in newsprint.", record: "It was a cover-up—of MOGUL's classified purpose, one of the Cold War's most sensitive programs. And in July 1947, 'flying disc' meant any unidentified object, not a spacecraft. The contradiction is real; the conclusion doesn't follow.", sourceIds: ["roswell-af"] },
      { title: "The missing launch log", theory: "Conveniently, no launch record survives for the exact MOGUL flight said to explain the debris—the official story rests on a gap.", record: "The gap is genuine and keeps the identification circumstantial. But the program, its materials, and its June 1947 New Mexico operations are thoroughly documented; the debris has a mundane candidate, and no exotic one has physical support.", sourceIds: ["roswell-report"] },
      { title: "The bodies", theory: "Multiple witnesses described small non-human bodies, a second crash site, and military threats to keep quiet.", record: "The body accounts surfaced 30–50 years after the event, conflict in core details, include exposed fabrications, and track documented 1950s dummy-drop and aircraft-accident events better than anything from 1947.", sourceIds: ["roswell-caseclosed"] }
    ],
    sources: [
      { id: "roswell-af", title: "The Roswell Report", publisher: "U.S. Air Force", type: "Official investigation", url: "https://www.af.mil/The-Roswell-Report/quot/" },
      { id: "roswell-report", title: "The Roswell Report: Fact versus Fiction in the New Mexico Desert", publisher: "Air Force History", type: "Document collection", url: "https://www.dafhistory.af.mil/Portals/16/documents/AFD-101201-038.pdf" },
      { id: "roswell-caseclosed", title: "The Roswell Report: Case Closed", publisher: "U.S. Air Force", type: "Follow-up report", url: "https://www.secretsdeclassified.af.mil/Portals/67/documents/AFD-100713-052.pdf" }
    ]
  },
  {
    slug: "dyatlov", title: "Dyatlov Pass", question: "Why did nine hikers leave their tent?",
    hook: "Nine experienced hikers cut their way out of a tent into a −25°C night, half-dressed, and walked toward the trees. None survived. The file was stamped 'compelling natural force.'",
    category: "Unexplained phenomena", reviewed: "July 2026",
    conventional: "A delayed slab-avalanche release—or the immediate threat of one—drove the group to cut out of the tent and retreat downslope. Darkness, wind, extreme cold, severe injuries from snow impact and a later ravine fall, and failed return attempts then killed all nine by trauma and hypothermia.",
    alternative: "Theories invoke secret weapons tests, an attack, infrasound-induced panic, katabatic winds, or stranger forces—citing the inside-out tent cut, the missing clothing, the crushing injuries with little external damage, reported orange lights, and traces of radioactivity.",
    readTime: "19 min",
    overview: "In late January 1959, ten students and graduates of the Ural Polytechnic Institute set out on a Grade III ski trek in the northern Urals; one turned back with illness. The remaining nine—led by Igor Dyatlov—were found dead over the following months, scattered between their cut-open tent on the slope of Kholat Syakhl and a ravine in the forest below. The Soviet investigation closed within three months citing an 'overwhelming natural force.' In 2021, the first peer-reviewed physical model showed a small delayed slab avalanche was possible on that slope.",
    story: [
      { heading: "The mountain of the dead", body: [
        "On 1 February 1959, the group pitched camp unusually high—on the open slope of Kholat Syakhl ('Dead Mountain' in the local Mansi language) rather than descending to the treeline. Diaries and photographs recovered later show a competent, cheerful team digging into the slope to level a platform for the tent, a standard technique that, in hindsight, may have cut the base out from under a wind-packed snow slab above them.",
        "Sometime that night, something made nine experienced winter hikers slash their way out of the tent from the inside and walk—not run, footprints show an orderly single file—nearly a mile downslope to the forest edge, most without boots, some in socks and underwear, into roughly −25°C and wind.",
        "Whatever it was, they judged it more dangerous than the cold. For an experienced group, that is a very short list of things." ] },
      { heading: "What the searchers found", body: [
        "When the group missed its check-in, searchers found the tent on 26 February: partially collapsed, cut open from inside, provisions and warm gear still in place. The first five bodies emerged over the following days—two under a cedar at the forest edge beside a dead fire, three on the slope between cedar and tent, as if struck down mid-climb trying to return. All five died of hypothermia; branches up the cedar were broken to about five metres, someone climbing for a view or for firewood.",
        "The last four were not found until May, under four metres of snow in a ravine streambed 75 metres deeper into the forest, on a floor of cut branches—a shelter. These bodies changed the story: a fractured skull, chest injuries a examining doctor compared to a car crash, and soft-tissue damage including missing eyes and tongue. Two of their garments carried traces of radioactive contamination.",
        "The criminal case closed in May 1959: no guilty party, an 'overwhelming natural force.' The files were archived, the pass was named for Dyatlov, and the vagueness of that phrase incubated theories for sixty years." ] },
      { heading: "Sixty years of theories", body: [
        "The inventory is famous: an avalanche (but the tent wasn't buried, the slope seemed too shallow, and the group's own tracks survived); a Mansi attack (no other footprints, no struggle); escaped prisoners (none escaped); infrasound from wind vortices inducing panic; secret missile or 'vacuum bomb' tests (orange lights were reported in the sky that winter, and there's the radioactivity); a romantic quarrel; a snow creature. Declassified files and a 2019–2020 Russian prosecutor's review rejected the criminal scenarios and settled on avalanche plus poor visibility—without showing the physics.",
        "Each alternative explains one or two details brilliantly and the rest poorly. The soft-tissue damage is expected postmortem change and scavenging in a snow-melt streambed. The radioactive traces likely reflect that two group members worked at a nuclear facility—though this remains the file's most genuinely odd loose end. The orange lights match documented R-7 rocket launches visible from the region, but on dates that don't align with the death night." ] },
      { heading: "The physics catches up", body: [
        "In 2021, two Swiss researchers—an avalanche dynamicist and a geotechnical engineer—published the first quantitative model of the night in Communications Earth & Environment. Using irregular local topography, wind-loading of snow above the cut tent platform, and delayed failure mechanics (with impact biomechanics calibrated, memorably, from crash-test data once used for the film Frozen's snow animation), they showed a small slab release hours after the cut was physically plausible—and that a metre-scale slab striking sleepers braced on skis could produce exactly the unusual chest and skull fractures with little external damage.",
        "A small slab also answers the classic objections: it wouldn't bury the tent, wouldn't erase tracks, and would leave a debris signature gone long before 26 February. Follow-up expeditions in 2022 photographed fresh slab releases on adjacent slopes of the pass, confirming the terrain produces them.",
        "The authors are careful: they proved possibility, not occurrence. But the sequence—cut platform, wind-loaded slope, night release or imminent-release panic, evacuation of injured friends to the treeline, a fire that failed, a shelter in a fatal ravine, and three who died climbing back for the tent—now explains more of the evidence with fewer assumptions than any rival. The mountain did it; the argument is only over exactly how." ] }
    ],
    sharedFacts: ["The tent was cut open from the inside and abandoned with boots, food, and warm clothing still in it.", "Footprints of eight or nine people, mostly shoeless, led in orderly fashion toward the forest.", "Five died of hypothermia; the four found in the ravine had major blunt-force trauma.", "Two garments carried traces of radioactive contamination.", "No footprints of outsiders and no signs of struggle were documented."],
    unresolved: ["The precise trigger—actual slab release, imminent-failure sounds, or something else—that forced the immediate exit.", "The sequence of the deaths and decisions between tent, cedar, and ravine.", "A fully satisfying account of the radiation traces on two garments.", "Whether the reported orange spheres relate to anything beyond documented rocket launches on other dates."],
    timeline: [
      { date: "23 Jan 1959", event: "The ten-member group departs Sverdlovsk; Yuri Yudin turns back ill on 28 January.", status: "Confirmed" },
      { date: "1 Feb 1959", event: "The group cuts a platform and camps on the open slope of Kholat Syakhl.", status: "Confirmed" },
      { date: "Night of 1–2 Feb", event: "All nine cut out of the tent and descend to the forest; none survive the night.", status: "Confirmed" },
      { date: "26 Feb 1959", event: "Searchers find the tent; five bodies are recovered in the following days.", status: "Confirmed" },
      { date: "4 May 1959", event: "The final four are found in a ravine shelter with severe trauma.", status: "Confirmed" },
      { date: "28 May 1959", event: "The investigation closes: an 'overwhelming natural force,' no guilty party.", status: "Confirmed" },
      { date: "Jul 2020", event: "A Russian prosecutor's review reaffirms an avalanche scenario, without physical modelling.", status: "Reported" },
      { date: "28 Jan 2021", event: "A peer-reviewed model shows a delayed slab avalanche was physically plausible.", status: "Confirmed" },
      { date: "2022", event: "Follow-up expeditions photograph fresh slab avalanches on adjacent slopes.", status: "Confirmed" }
    ],
    evidenceCards: [
      { title: "Why they cut their way out", theory: "No avalanche was found—the tent wasn't buried, the slope looked too shallow, and their own footprints survived. Something else drove them out.", record: "The 2021 model shows a small delayed slab—released hours after they cut the slope for their platform—was physically possible, wouldn't bury the tent, wouldn't erase tracks, and would leave no trace by 26 February. 2022 expeditions photographed fresh slabs on adjacent slopes.", sourceIds: ["dyatlov-study", "dyatlov-followup"] },
      { title: "The crushing injuries", theory: "Ribcages and a skull fractured 'like a car crash' with almost no external damage—no fall or snow does that; a blast wave or violence does.", record: "Impact biomechanics show a compact slab striking sleepers braced on ski-floor bedding reproduces exactly this pattern; burial under four metres of ravine snow can do the rest. The three-month recovery delay complicates every reading—this point lands closer to a draw than either side admits.", sourceIds: ["dyatlov-study"] },
      { title: "The calm walk to their deaths", theory: "Nine people don't walk single-file into −25°C without boots unless something terrifying—or someone—forced them.", record: "Orderly single-file evacuation is precisely what avalanche training prescribes: get off the loaded slope, now, together. The tracks show discipline, not flight from an attacker—no other footprints were ever found.", sourceIds: ["dyatlov-study"] },
      { title: "The radiation and the lights", theory: "Radioactive clothing and orange spheres in the sky point to a weapons test the Soviets buried—explaining the vague verdict and the sealed files.", record: "Two of the group worked in the nuclear industry; the documented rocket launches visible that winter fall on other dates; and no weapon debris, blast damage, or test record has ever been tied to the site. The contamination remains the file's oddest loose end—but it anchors nothing.", sourceIds: ["dyatlov-study"] }
    ],
    sources: [
      { id: "dyatlov-study", title: "Mechanisms of slab avalanche release and impact in the Dyatlov Pass incident", publisher: "Communications Earth & Environment", type: "Peer-reviewed study", url: "https://www.nature.com/articles/s43247-020-00081-8" },
      { id: "dyatlov-followup", title: "Follow-up expeditions reveal avalanches at Dyatlov Pass", publisher: "Communications Earth & Environment", type: "Scientific follow-up", url: "https://www.nature.com/articles/s43247-022-00393-x" }
    ]
  },
  {
    slug: "atlantis", title: "Atlantis", question: "Was Plato describing a real civilization?",
    hook: "One philosopher, writing 2,400 years ago, invented—or preserved—an empire beyond the Pillars of Heracles. Every generation since has gone looking for it.",
    category: "Archaeology", reviewed: "July 2026",
    conventional: "Most classicists read Atlantis as a philosophical invention within Plato's Timaeus and Critias: a wealthy, aggressive naval empire built to lose against an idealized ancient Athens, illustrating his political theory before being destroyed for its decline into greed.",
    alternative: "Some researchers argue Plato preserved a distorted memory of a real place or catastrophe—proposing Minoan Thera, Iberian Tartessos, North Africa, or submerged Atlantic sites as the kernel behind the story.",
    readTime: "17 min",
    overview: "Atlantis enters the written record in exactly two places: Plato's dialogues Timaeus and Critias, composed around 360 BCE. In the story, Egyptian priests tell the Athenian statesman Solon of a vast island power that attacked the Mediterranean nine thousand years earlier and sank 'in a single dreadful day and night.' No earlier text, Egyptian record, or archaeological site independently attests it—yet the search has never stopped.",
    story: [
      { heading: "Two dialogues and a dare", body: [
        "Around 360 BCE, Plato wrote a pair of linked dialogues. In Timaeus, the character Critias relates a story he says came down from his great-grandfather, who heard it from Solon, who heard it from priests at Saïs in Egypt: nine thousand years before, a mighty island empire 'larger than Libya and Asia together,' lying beyond the Pillars of Heracles, attacked the free peoples of the Mediterranean—and was defeated by a heroic, primeval Athens, before earthquakes and floods swallowed the island in a day and a night.",
        "In Critias, Plato lays out the empire in astonishing detail: concentric rings of land and sea, walls sheathed in precious orichalcum, a temple to Poseidon, ten kings descended from the god, elephants, canals, a plain of impossible dimensions. Then—mid-sentence, as Zeus rises to pronounce judgment on the Atlanteans' moral decay—the dialogue simply stops. Plato never finished it.",
        "That is the entire ancient evidence. Every book, documentary, and expedition since rests on those two texts." ] },
      { heading: "What the story is for", body: [
        "Read in context, Atlantis has a job to do. Plato had described his ideal state in the Republic; the Timaeus-Critias project sets that ideal city in motion, showing virtuous proto-Athens—Plato's constitution in action—defeating a decadent superpower. Atlantis is the anti-Athens: wealthy beyond measure, technologically dazzling, morally rotting. Its sinking is a parable about divine judgment on imperial hubris, aimed squarely at the seafaring Athens of Plato's own day.",
        "Ancient readers noticed. Aristotle, Plato's own student, is traditionally credited with the remark that the man who invented Atlantis also destroyed it. No Greek historian treated it as history; no Egyptian text mentions it; Herodotus, who visited Egypt a century before Plato wrote and collected everything the priests told him, records nothing of the kind.",
        "The 'nine thousand years' is itself a tell: it places a marble-temple, bronze-armor civilization seven millennia before cities, writing, or bronze existed anywhere." ] },
      { heading: "The candidates", body: [
        "The strongest 'kernel' candidate is the eruption of Thera (Santorini) around 1600 BCE—a real island civilization shattered by a real cataclysm, whose tsunamis battered Minoan Crete. The parallels are evocative: a sophisticated maritime culture, sudden destruction, a caldera's ring-like geography. But the fit requires dividing Plato's date by ten, shrinking his continent a hundredfold, and relocating it from the Atlantic to the Aegean—at which point the theory is no longer matching the text but rewriting it.",
        "Other proposals—Tartessos in Iberia, the Rif coast of Morocco, Doggerland, the Azores, Antarctica, the Bahamas' Bimini Road—each seize a detail (beyond the Pillars! a sunken plain! stone formations!) and quietly drop the rest. The Bimini Road is natural beachrock; no submerged city has surfaced anywhere it should.",
        "Meanwhile, ignoring Plato's clear framing has costs he would have appreciated: the ancient-aliens and lost-super-civilization industries built on Atlantis routinely strip real achievements from real ancient peoples and hand them to a fantasy." ] },
      { heading: "Why it never sinks", body: [
        "Atlantis endures because it is a perfect story-shaped hole. Ignatius Donnelly's 1882 bestseller turned it into pseudo-archaeology's founding text; occultists made it a lost golden age; fiction made it a genre. Every era refits it—imperial cautionary tale, drowned Eden, alien colony—because Plato built it from durable parts: lost greatness, sudden judgment, secrets under the sea.",
        "The irony is that the true mystery is textual and quite real: we do not actually know where Plato got his materials, why he anchored the tale in an Egyptian transmission chain, or why Critias breaks off unfinished. Those are answerable scholarly questions with a genuine gap in the record. The continent, though, stays where Plato put it—in an unfinished book." ] }
    ],
    sharedFacts: ["The only ancient sources are Plato's Timaeus and Critias, c. 360 BCE.", "The story functions as a political-philosophical contrast with an idealized Athens.", "Critias breaks off mid-sentence, unfinished.", "No Egyptian record or earlier Greek text independently attests Atlantis.", "No proposed site satisfies the text's date, scale, and location together with archaeology."],
    unresolved: ["Which real events, myths, or places—if any—supplied Plato's raw material.", "Whether Plato intended any part of the Solon transmission story to be taken as fact.", "Why Critias was left unfinished.", "How the Thera eruption's memory did or did not persist into classical Greece."],
    timeline: [
      { date: "c. 1600 BCE", event: "The Thera eruption devastates the Aegean—the favorite candidate for a historical 'kernel.'", status: "Confirmed" },
      { date: "c. 590 BCE", event: "Solon visits Egypt—the anchor of the story's claimed transmission chain.", status: "Reported" },
      { date: "c. 360 BCE", event: "Plato composes Timaeus and Critias, the sole ancient sources.", status: "Confirmed" },
      { date: "4th c. BCE", event: "Aristotle is credited with treating Atlantis as Plato's invention; no ancient historian records it as fact.", status: "Reported" },
      { date: "1882", event: "Ignatius Donnelly's 'Atlantis: The Antediluvian World' launches the modern search.", status: "Confirmed" },
      { date: "20th–21st c.", event: "Thera, Iberia, the Bahamas, Antarctica and dozens more sites are proposed; none is archaeologically confirmed.", status: "Confirmed" }
    ],
    evidenceCards: [
      { title: "Where the story comes from", theory: "Plato says it plainly: the priests of Saïs told Solon a true history, passed down through his own family. Why would he fabricate a lineage?", record: "The entire narrative rests on two dialogues by one philosopher. No Egyptian record, no earlier Greek text—and Herodotus, who canvassed the same Egyptian priests a century before Plato wrote, records nothing. Invented pedigrees were a standard literary device Plato used elsewhere.", sourceIds: ["atl-timaeus", "atl-critias"] },
      { title: "The suspiciously perfect villain", theory: "A story can be philosophically useful and still be true—ancient authors constantly moralized real history.", record: "Atlantis is the exact anti-Athens Plato's political project required, its 9,000-year date puts marble temples seven millennia before agriculture, and his own student reportedly treated it as invention. Every structural signal says parable.", sourceIds: ["atl-iep", "atl-study"] },
      { title: "The Thera connection", theory: "A dazzling island civilization really was destroyed by a Bronze Age cataclysm the Greeks could remember—Plato just garbled the details.", record: "The motifs are genuinely evocative, and this is the theory's strongest card. But the match requires dividing Plato's date by ten, shrinking his continent a hundredfold, and moving it from the Atlantic to the Aegean—rewriting the text, not reading it.", sourceIds: ["atl-study"] },
      { title: "The 'found Atlantis' claims", theory: "Bimini's stone roads, Iberian marshes, Santorini's rings, sonar shapes off Cuba—candidates keep surfacing.", record: "Every examined 'ruin' has proven natural or misdated; no site has produced an inscription, artifact, or chronology matching the text. A century and a half of searching has confirmed nothing.", sourceIds: ["atl-critias"] }
    ],
    sources: [
      { id: "atl-timaeus", title: "Timaeus", publisher: "Perseus Digital Library", type: "Primary ancient text", url: "https://catalog.perseus.tufts.edu/catalog/urn:cts:greekLit:tlg0059.tlg031.perseus-eng1" },
      { id: "atl-critias", title: "Critias", publisher: "MIT Internet Classics Archive", type: "Primary ancient text", url: "https://classics.mit.edu/Plato/critias.html" },
      { id: "atl-iep", title: "Plato: The Timaeus", publisher: "Internet Encyclopedia of Philosophy", type: "Academic reference", url: "https://iep.utm.edu/timaeus/" },
      { id: "atl-study", title: "Plato's Atlantis", publisher: "L'Antiquité Classique / Persée", type: "Academic analysis", url: "https://www.persee.fr/doc/antiq_0770-2817_1982_num_51_1_2060" }
    ]
  }
];
